platform :ios, '13.5'

target 'atlas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for atlas

  target 'atlasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'atlasUITests' do
    # Pods for testing
  end

end
