
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache gradle
      uses: actions/cache@v2.1.0
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up cocoapods-generate
      run: gem install cocoapods-generate
    - name: Set up local secrets
      env:
        MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
        MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
      run: |
        echo mapbox.key="$MAPBOX_KEY" > local.properties
        echo server.url=https://example.com/ >> local.properties
        echo MAPBOX_DOWNLOADS_TOKEN=$MAPBOX_DOWNLOADS_TOKEN >> ~/.gradle/gradle.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew check 
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Install pods
      working-directory: ./ios
      run: pod install
    - name: Run xcodebuild
      run: xcodebuild -sdk iphonesimulator -destination "name=iPhone 11,OS=14.0" -workspace ios/atlas.xcworkspace -configuration Debug -scheme atlas build
