
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set up cocoapods-generate
      run: gem install cocoapods-generate
    - name: Set up local secrets
      env:
        MAPBOX_KEY: ${{ secrets.MAPBOX_KEY }}
      run: echo mapbox.key="$MAPBOX_KEY" > local.properties
    - name: Configure server endpoint
      run: echo server.url=https://example.com/ > local.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew check
